## Near Telegram Data Extract Transform Load

Get a list of all files.

In [ ]:
import glob

json_files = glob.glob("./data/Telegram Data/*")
json_files

Investigate a single file.

In [ ]:
import json

with open(json_files[0]) as file:
    data = json.load(file)
data.keys()

In [3]:
import pandas as pd
pd.DataFrame(data)

,name,type,id,messages
0,NxM 🎶,public_supergroup,1235117278,"{'id': 1, 'type': 'service', 'date': '2021-02-..."
1,NxM 🎶,public_supergroup,1235117278,"{'id': 2, 'type': 'message', 'date': '2021-02-..."
2,NxM 🎶,public_supergroup,1235117278,"{'id': 3, 'type': 'message', 'date': '2021-02-..."
3,NxM 🎶,public_supergroup,1235117278,"{'id': 4, 'type': 'message', 'date': '2021-02-..."
4,NxM 🎶,public_supergroup,1235117278,"{'id': 5, 'type': 'message', 'date': '2021-02-..."
...,...,...,...,...
11767,NxM 🎶,public_supergroup,1235117278,"{'id': 11932, 'type': 'message', 'date': '2021..."
11768,NxM 🎶,public_supergroup,1235117278,"{'id': 11933, 'type': 'message', 'date': '2021..."
11769,NxM 🎶,public_supergroup,1235117278,"{'id': 11934, 'type': 'message', 'date': '2021..."
11770,NxM 🎶,public_supergroup,1235117278,"{'id': 11935, 'type': 'message', 'date': '2021..."
11771,NxM 🎶,public_supergroup,1235117278,"{'id': 11936, 'type': 'message', 'date': '2021..."

Load the messages data as a dataframe.

In [4]:
df = pd.DataFrame(data['messages'])
df['data_name'] = data['name']
df['data_type'] = data['type']
df['data_id'] = data['id']
df

,id,type,date,actor,actor_id,action,title,text,from,from_id,...,address,location_information,contact_information,author,saved_from,duration,schedule_date,data_name,data_type,data_id
0,1,service,2021-02-28T12:04:46,NxM 🎶,channel1235117278,migrate_from_group,NxM 🎶,,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NxM 🎶,public_supergroup,1235117278
1,2,message,2021-02-28T12:05:17,NaN,NaN,NaN,NaN,I've changed the 'previous messages' setting. ...,Vandal |DAOrecords,user322917593,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NxM 🎶,public_supergroup,1235117278
2,3,message,2021-02-28T13:01:18,NaN,NaN,NaN,NaN,"[Hey guys, I’m Kemo from berlin and new here, ...",Kemo,user437784134,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NxM 🎶,public_supergroup,1235117278
3,4,message,2021-02-28T13:35:59,NaN,NaN,NaN,NaN,Hey man! Living in Berlin as well!,Justin || will never dm first,user1604289539,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NxM 🎶,public_supergroup,1235117278
4,5,message,2021-02-28T13:37:23,NaN,NaN,NaN,NaN,"[{'type': 'mention_name', 'text': 'Mina', 'use...",Carolin W.,user772374289,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NxM 🎶,public_supergroup,1235117278
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11767,11932,message,2021-11-17T13:23:19,NaN,NaN,NaN,NaN,Wish am there but u need a laptop so imma show...,Jahbeacons.page/jahzonemusic Zone,user1539930840,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NxM 🎶,public_supergroup,1235117278
11768,11933,message,2021-11-17T13:24:04,NaN,NaN,NaN,NaN,Just there but not giving the way I want,Jahbeacons.page/jahzonemusic Zone,user1539930840,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NxM 🎶,public_supergroup,1235117278
11769,11934,message,2021-11-17T13:24:26,NaN,NaN,NaN,NaN,Grooving*,Jahbeacons.page/jahzonemusic Zone,user1539930840,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NxM 🎶,public_supergroup,1235117278
11770,11935,message,2021-11-17T16:20:19,NaN,NaN,NaN,NaN,Someone should feature me now,Midasdave,user1235754333,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NxM 🎶,public_supergroup,1235117278
11771,11936,message,2021-11-17T16:22:09,NaN,NaN,NaN,NaN,"[Check me out on audiomack , {'type': 'mention...",Midasdave,user1235754333,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NxM 🎶,public_supergroup,1235117278

Looks like we have some NaN. Let's check.

In [5]:
df.isna().sum() / len(df)

id                      0.000000
type                    0.000000
date                    0.000000
actor                   0.962113
actor_id                0.961774
action                  0.961774
title                   0.998811
text                    0.000000
from                    0.041794
from_id                 0.038226
reply_to_message_id     0.685695
edited                  0.985134
forwarded_from          0.990231
members                 0.973496
file                    0.973921
media_type              0.974346
mime_type               0.987428
duration_seconds        0.987853
width                   0.953534
height                  0.953534
inviter                 0.990826
thumbnail               0.980802
sticker_emoji           0.986748
photo                   0.978084
poll                    0.999235
message_id              0.998131
via_bot                 0.996262
performer               0.998981
place_name              0.999915
address                 0.999915
location_information    0.999915
contact_information     0.999915
author                  0.998386
saved_from              0.995583
duration                0.999830
schedule_date           0.999745
data_name               0.000000
data_type               0.000000
data_id                 0.000000
dtype: float64

Let's check all the files.

In [6]:
data_frames = []
for json_file in json_files:
    with open(json_file) as file:
        data = json.load(file)
    df = pd.DataFrame(data['messages'])
    df['data_name'] = data['name']
    df['data_type'] = data['type']
    df['data_id'] = data['id']
    data_frames.append(df)

In [7]:
all_data = pd.concat(data_frames)

In [8]:
all_data

,id,type,date,actor,actor_id,action,title,text,from,from_id,...,location_information,contact_information,author,saved_from,duration,schedule_date,data_name,data_type,data_id,contact_vcard
0,1,service,2021-02-28T12:04:46,NxM 🎶,channel1235117278,migrate_from_group,NxM 🎶,,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NxM 🎶,public_supergroup,1235117278,NaN
1,2,message,2021-02-28T12:05:17,NaN,NaN,NaN,NaN,I've changed the 'previous messages' setting. ...,Vandal |DAOrecords,user322917593,...,NaN,NaN,NaN,NaN,NaN,NaN,NxM 🎶,public_supergroup,1235117278,NaN
2,3,message,2021-02-28T13:01:18,NaN,NaN,NaN,NaN,"[Hey guys, I’m Kemo from berlin and new here, ...",Kemo,user437784134,...,NaN,NaN,NaN,NaN,NaN,NaN,NxM 🎶,public_supergroup,1235117278,NaN
3,4,message,2021-02-28T13:35:59,NaN,NaN,NaN,NaN,Hey man! Living in Berlin as well!,Justin || will never dm first,user1604289539,...,NaN,NaN,NaN,NaN,NaN,NaN,NxM 🎶,public_supergroup,1235117278,NaN
4,5,message,2021-02-28T13:37:23,NaN,NaN,NaN,NaN,"[{'type': 'mention_name', 'text': 'Mina', 'use...",Carolin W.,user772374289,...,NaN,NaN,NaN,NaN,NaN,NaN,NxM 🎶,public_supergroup,1235117278,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5878,5852,message,2021-11-17T07:27:47,NaN,NaN,NaN,NaN,yes agreed,Maria Magdalena,user1764971579,...,NaN,NaN,NaN,NaN,NaN,NaN,Creatives DAO Chat,public_supergroup,1463257013,NaN
5879,5853,message,2021-11-17T08:22:50,NaN,NaN,NaN,NaN,💞 thanks for the feedback. The goal is to hope...,chloethedev (She/Her),user1028580551,...,NaN,NaN,NaN,NaN,NaN,NaN,Creatives DAO Chat,public_supergroup,1463257013,NaN
5880,5854,message,2021-11-17T08:55:09,NaN,NaN,NaN,NaN,Beautiful,Jaswinder Singh,user1100971771,...,NaN,NaN,NaN,NaN,NaN,NaN,Creatives DAO Chat,public_supergroup,1463257013,NaN
5881,5855,message,2021-11-17T09:39:09,NaN,NaN,NaN,NaN,"[New NFT project on NEAR. Looks Rare: , {'type...",Crypto G,user1793664445,...,NaN,NaN,NaN,NaN,NaN,NaN,Creatives DAO Chat,public_supergroup,1463257013,NaN
5882,5856,message,2021-11-17T12:34:09,NaN,NaN,NaN,NaN,"[{'type': 'link', 'text': 'https://twitter.com...",chloethedev (She/Her),user1028580551,...,NaN,NaN,NaN,NaN,NaN,NaN,Creatives DAO Chat,public_supergroup,1463257013,NaN

In [9]:
all_data.isna().sum() / len(all_data)

id                      0.000000
type                    0.000000
date                    0.000000
actor                   0.939832
actor_id                0.927770
action                  0.927770
title                   0.999851
text                    0.000000
from                    0.096435
from_id                 0.072230
reply_to_message_id     0.567308
edited                  0.961848
forwarded_from          0.990211
members                 0.929676
file                    0.958900
media_type              0.960304
mime_type               0.987727
duration_seconds        0.989131
width                   0.928928
height                  0.928928
inviter                 0.999650
thumbnail               0.963582
sticker_emoji           0.971328
photo                   0.969681
poll                    0.999708
message_id              0.998874
via_bot                 0.998639
performer               0.999928
place_name              0.999997
address                 0.999997
location_information    0.999997
contact_information     0.999994
author                  0.998548
saved_from              0.997447
duration                0.999894
schedule_date           0.999891
data_name               0.000000
data_type               0.000000
data_id                 0.000000
contact_vcard           0.999997
dtype: float64

Drop columns with more than 90% NaN

In [10]:
data_90 = all_data[['id', 'type', 'date', 'text', 'from', 'from_id', 'reply_to_message_id', 'data_name', 'data_type', 'data_id']]
data_90

,id,type,date,text,from,from_id,reply_to_message_id,data_name,data_type,data_id
0,1,service,2021-02-28T12:04:46,,NaN,NaN,NaN,NxM 🎶,public_supergroup,1235117278
1,2,message,2021-02-28T12:05:17,I've changed the 'previous messages' setting. ...,Vandal |DAOrecords,user322917593,NaN,NxM 🎶,public_supergroup,1235117278
2,3,message,2021-02-28T13:01:18,"[Hey guys, I’m Kemo from berlin and new here, ...",Kemo,user437784134,NaN,NxM 🎶,public_supergroup,1235117278
3,4,message,2021-02-28T13:35:59,Hey man! Living in Berlin as well!,Justin || will never dm first,user1604289539,NaN,NxM 🎶,public_supergroup,1235117278
4,5,message,2021-02-28T13:37:23,"[{'type': 'mention_name', 'text': 'Mina', 'use...",Carolin W.,user772374289,NaN,NxM 🎶,public_supergroup,1235117278
...,...,...,...,...,...,...,...,...,...,...
5878,5852,message,2021-11-17T07:27:47,yes agreed,Maria Magdalena,user1764971579,NaN,Creatives DAO Chat,public_supergroup,1463257013
5879,5853,message,2021-11-17T08:22:50,💞 thanks for the feedback. The goal is to hope...,chloethedev (She/Her),user1028580551,5851.0,Creatives DAO Chat,public_supergroup,1463257013
5880,5854,message,2021-11-17T08:55:09,Beautiful,Jaswinder Singh,user1100971771,5853.0,Creatives DAO Chat,public_supergroup,1463257013
5881,5855,message,2021-11-17T09:39:09,"[New NFT project on NEAR. Looks Rare: , {'type...",Crypto G,user1793664445,NaN,Creatives DAO Chat,public_supergroup,1463257013
5882,5856,message,2021-11-17T12:34:09,"[{'type': 'link', 'text': 'https://twitter.com...",chloethedev (She/Her),user1028580551,NaN,Creatives DAO Chat,public_supergroup,1463257013

Drop columns with more than 98% NaN

In [11]:
data_98 = all_data[['id', 'type', 'date', 'actor', 'actor_id', 'text', 'from', 'from_id', 'reply_to_message_id', 'edited', 'members', 'file', 'media_type', 'width', 'height', 'thumbnail', 'sticker_emoji', 'photo',  'data_name', 'data_type', 'data_id']]
data_98

,id,type,date,actor,actor_id,text,from,from_id,reply_to_message_id,edited,...,file,media_type,width,height,thumbnail,sticker_emoji,photo,data_name,data_type,data_id
0,1,service,2021-02-28T12:04:46,NxM 🎶,channel1235117278,,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NxM 🎶,public_supergroup,1235117278
1,2,message,2021-02-28T12:05:17,NaN,NaN,I've changed the 'previous messages' setting. ...,Vandal |DAOrecords,user322917593,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NxM 🎶,public_supergroup,1235117278
2,3,message,2021-02-28T13:01:18,NaN,NaN,"[Hey guys, I’m Kemo from berlin and new here, ...",Kemo,user437784134,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NxM 🎶,public_supergroup,1235117278
3,4,message,2021-02-28T13:35:59,NaN,NaN,Hey man! Living in Berlin as well!,Justin || will never dm first,user1604289539,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NxM 🎶,public_supergroup,1235117278
4,5,message,2021-02-28T13:37:23,NaN,NaN,"[{'type': 'mention_name', 'text': 'Mina', 'use...",Carolin W.,user772374289,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NxM 🎶,public_supergroup,1235117278
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5878,5852,message,2021-11-17T07:27:47,NaN,NaN,yes agreed,Maria Magdalena,user1764971579,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Creatives DAO Chat,public_supergroup,1463257013
5879,5853,message,2021-11-17T08:22:50,NaN,NaN,💞 thanks for the feedback. The goal is to hope...,chloethedev (She/Her),user1028580551,5851.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Creatives DAO Chat,public_supergroup,1463257013
5880,5854,message,2021-11-17T08:55:09,NaN,NaN,Beautiful,Jaswinder Singh,user1100971771,5853.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Creatives DAO Chat,public_supergroup,1463257013
5881,5855,message,2021-11-17T09:39:09,NaN,NaN,"[New NFT project on NEAR. Looks Rare: , {'type...",Crypto G,user1793664445,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Creatives DAO Chat,public_supergroup,1463257013
5882,5856,message,2021-11-17T12:34:09,NaN,NaN,"[{'type': 'link', 'text': 'https://twitter.com...",chloethedev (She/Her),user1028580551,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Creatives DAO Chat,public_supergroup,1463257013

In [12]:
data_16 = data_98.dropna(thresh=16)
data_16

,id,type,date,actor,actor_id,text,from,from_id,reply_to_message_id,edited,...,file,media_type,width,height,thumbnail,sticker_emoji,photo,data_name,data_type,data_id
334,336,message,2021-03-05T14:42:09,NaN,NaN,,NiMA ~~~ 💤,user113955403,334.0,NaN,...,(File not included. Change data exporting sett...,sticker,512.0,512.0,(File not included. Change data exporting sett...,🙂,NaN,NxM 🎶,public_supergroup,1235117278
499,501,message,2021-03-13T12:16:23,NaN,NaN,,ADOR Mark,user469022154,499.0,NaN,...,(File not included. Change data exporting sett...,sticker,512.0,512.0,(File not included. Change data exporting sett...,🔥,NaN,NxM 🎶,public_supergroup,1235117278
657,659,message,2021-03-16T00:03:49,NaN,NaN,,chloethedev (She/Her),user1028580551,657.0,NaN,...,(File not included. Change data exporting sett...,sticker,512.0,512.0,(File not included. Change data exporting sett...,😍,NaN,NxM 🎶,public_supergroup,1235117278
894,896,message,2021-03-22T11:21:28,NaN,NaN,,IG @ebube_gram,user1278655320,894.0,NaN,...,(File not included. Change data exporting sett...,sticker,512.0,512.0,(File not included. Change data exporting sett...,❤️,NaN,NxM 🎶,public_supergroup,1235117278
900,902,message,2021-03-22T13:55:33,NaN,NaN,,IG @ebube_gram,user1278655320,901.0,NaN,...,(File not included. Change data exporting sett...,sticker,512.0,512.0,(File not included. Change data exporting sett...,👌,NaN,NxM 🎶,public_supergroup,1235117278
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5316,5284,message,2021-11-08T12:58:19,NaN,NaN,,Rebecca Hallquist (slow response),user1652051847,5274.0,NaN,...,(File not included. Change data exporting sett...,sticker,512.0,512.0,(File not included. Change data exporting sett...,🔥,NaN,Creatives DAO Chat,public_supergroup,1463257013
5456,5425,message,2021-11-08T15:59:14,NaN,NaN,,chloethedev (She/Her),user1028580551,5424.0,NaN,...,(File not included. Change data exporting sett...,sticker,512.0,512.0,(File not included. Change data exporting sett...,🤩,NaN,Creatives DAO Chat,public_supergroup,1463257013
5597,5569,message,2021-11-12T19:23:27,NaN,NaN,,chloethedev (She/Her),user1028580551,5568.0,NaN,...,(File not included. Change data exporting sett...,sticker,512.0,512.0,(File not included. Change data exporting sett...,✌️,NaN,Creatives DAO Chat,public_supergroup,1463257013
5639,5611,message,2021-11-15T09:11:58,NaN,NaN,,Monish o7,user656740966,5610.0,NaN,...,(File not included. Change data exporting sett...,sticker,512.0,512.0,(File not included. Change data exporting sett...,👍,NaN,Creatives DAO Chat,public_supergroup,1463257013
5858,5832,message,2021-11-16T14:56:06,NaN,NaN,,chloethedev (She/Her),user1028580551,5831.0,NaN,...,(File not included. Change data exporting sett...,sticker,512.0,512.0,(File not included. Change data exporting sett...,🥲,NaN,Creatives DAO Chat,public_supergroup,1463257013

In [13]:
data_16.isna().sum() / len(data_16)

id                     0.00000
type                   0.00000
date                   0.00000
actor                  1.00000
actor_id               1.00000
text                   0.00000
from                   0.00000
from_id                0.00000
reply_to_message_id    0.00000
edited                 0.99878
members                1.00000
file                   0.00000
media_type             0.00000
width                  0.00000
height                 0.00000
thumbnail              0.00000
sticker_emoji          0.00122
photo                  1.00000
data_name              0.00000
data_type              0.00000
data_id                0.00000
dtype: float64

In [14]:
some_clean_telegram_data = data_16.drop(['actor', 'actor_id', 'edited', 'members', 'photo'], axis=1)
some_clean_telegram_data

,id,type,date,text,from,from_id,reply_to_message_id,file,media_type,width,height,thumbnail,sticker_emoji,data_name,data_type,data_id
334,336,message,2021-03-05T14:42:09,,NiMA ~~~ 💤,user113955403,334.0,(File not included. Change data exporting sett...,sticker,512.0,512.0,(File not included. Change data exporting sett...,🙂,NxM 🎶,public_supergroup,1235117278
499,501,message,2021-03-13T12:16:23,,ADOR Mark,user469022154,499.0,(File not included. Change data exporting sett...,sticker,512.0,512.0,(File not included. Change data exporting sett...,🔥,NxM 🎶,public_supergroup,1235117278
657,659,message,2021-03-16T00:03:49,,chloethedev (She/Her),user1028580551,657.0,(File not included. Change data exporting sett...,sticker,512.0,512.0,(File not included. Change data exporting sett...,😍,NxM 🎶,public_supergroup,1235117278
894,896,message,2021-03-22T11:21:28,,IG @ebube_gram,user1278655320,894.0,(File not included. Change data exporting sett...,sticker,512.0,512.0,(File not included. Change data exporting sett...,❤️,NxM 🎶,public_supergroup,1235117278
900,902,message,2021-03-22T13:55:33,,IG @ebube_gram,user1278655320,901.0,(File not included. Change data exporting sett...,sticker,512.0,512.0,(File not included. Change data exporting sett...,👌,NxM 🎶,public_supergroup,1235117278
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5316,5284,message,2021-11-08T12:58:19,,Rebecca Hallquist (slow response),user1652051847,5274.0,(File not included. Change data exporting sett...,sticker,512.0,512.0,(File not included. Change data exporting sett...,🔥,Creatives DAO Chat,public_supergroup,1463257013
5456,5425,message,2021-11-08T15:59:14,,chloethedev (She/Her),user1028580551,5424.0,(File not included. Change data exporting sett...,sticker,512.0,512.0,(File not included. Change data exporting sett...,🤩,Creatives DAO Chat,public_supergroup,1463257013
5597,5569,message,2021-11-12T19:23:27,,chloethedev (She/Her),user1028580551,5568.0,(File not included. Change data exporting sett...,sticker,512.0,512.0,(File not included. Change data exporting sett...,✌️,Creatives DAO Chat,public_supergroup,1463257013
5639,5611,message,2021-11-15T09:11:58,,Monish o7,user656740966,5610.0,(File not included. Change data exporting sett...,sticker,512.0,512.0,(File not included. Change data exporting sett...,👍,Creatives DAO Chat,public_supergroup,1463257013
5858,5832,message,2021-11-16T14:56:06,,chloethedev (She/Her),user1028580551,5831.0,(File not included. Change data exporting sett...,sticker,512.0,512.0,(File not included. Change data exporting sett...,🥲,Creatives DAO Chat,public_supergroup,1463257013

In [16]:
some_clean_telegram_data.to_csv('outputs/some_clean_telegram_data.csv', index=False)